### ISSUE TITLE
CLI input in API?

### ISSUE THREAD

**Issue by llmuculusll** [smrrazavian/APIs#1]
That is very weird API App.
I remember you should write an endpoint that gives two numbers, but you write a code that gives two numbers from CLI!
Please rewrite your code.

**Comment by smrrazavian** [comment]
Hi,
Thank you
is it ok now?

**Comment by llmuculusll** [comment]
Unfortunately no,
As I said before, your web service should has two input parameters. But you define two hardcode variables!
